name: Spring Boot SBOM Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v3

      # --------------------------
      # 1. Build-time SBOM (Maven)
      # --------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Generate Maven SBOM
        run: mvn cyclonedx:makeAggregateBom

#      - name: Upload Maven SBOM
#        run: |
#          curl -X POST -F "file=@target/bom.json" https://sbom.irembo.org/api/upload

      # --------------------------
      # 2. Container SBOM (Syft)
      # --------------------------
      #- name: Log in to Docker (optional if pushing)
      #  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

  #    - name: Build Docker image
   #     run: docker build -t my-app:latest .

    #  - name: Generate Container SBOM
     #   uses: anchore/syft-action@v0.5.0
      #  with:
       #   image: my-app:latest
        #  format: cyclonedx-json
         # output: sbom-container.json

 #     - name: Upload Container SBOM
 #       run: |
  #        curl -X POST -F "file=@sbom-container.json" https://sbom.irembo.org/api/upload

